/* data load */
INSERT INTO ROOM (ROOM_CD, FLOOR_NBR, ROOM_NM, ROOM_DESC, ROOM_SEATS_NBR) VALUES ( 'RAMS-4', 4, 'Rams', 'Rams room', 20 );
INSERT INTO ROOM (ROOM_CD, FLOOR_NBR, ROOM_NM, ROOM_DESC, ROOM_SEATS_NBR) VALUES ( 'CARDINALS-4', 4, 'Cardinals', 'Cardinals room', 30 );

INSERT INTO COURSE (COURSE_CD, COURSE_NM, COURSE_DESC) VALUES ( 'JAVACOURSE', 'Java Course', 'Java Course' );
INSERT INTO COURSE (COURSE_CD, COURSE_NM, COURSE_DESC) VALUES ( 'DOTNETCOURSE', 'DotNet Course', 'DotNet Course' );

INSERT INTO CLASS (CLASS_CD, CLASS_NM, CLASS_DESC, COURSE_ID) VALUES ('JAVA101', 'Java 101', 'Introduction to Java 101', 1);
INSERT INTO CLASS (CLASS_CD, CLASS_NM, CLASS_DESC, COURSE_ID) VALUES ('JAVA102', 'Java 102', 'Introduction to Java 102', 1);
INSERT INTO CLASS (CLASS_CD, CLASS_NM, CLASS_DESC, COURSE_ID) VALUES ('JAVA103', 'Java 103', 'Introduction to Java 103', 1);
INSERT INTO CLASS (CLASS_CD, CLASS_NM, CLASS_DESC, COURSE_ID) VALUES ('DOTNET101', 'DotNet 101', 'Introduction to DotNet 101', 2);
INSERT INTO CLASS (CLASS_CD, CLASS_NM, CLASS_DESC, COURSE_ID) VALUES ('DOTNET102', 'DotNet 102', 'Introduction to DotNet 102', 2);
INSERT INTO CLASS (CLASS_CD, CLASS_NM, CLASS_DESC, COURSE_ID) VALUES ('DOTNET103', 'DotNet 103', 'Introduction to DotNet 103', 2);

INSERT INTO PERSON (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONE_SMS, EMAIL, ACTIVE_IND) VALUES ('Brad.Busch', 'password', 'Brad', 'Busch', 5555555555, 'brad.busch@daugherty.com', 1);
INSERT INTO PERSON (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONE_SMS, EMAIL, ACTIVE_IND) VALUES ('John.Day', 'password', 'John', 'Day', 4174991559, 'john.day@daugherty.com', 1);
INSERT INTO PERSON (USERNAME, PASSWORD, FIRSTNAME, LASTNAME, PHONE_SMS, EMAIL, ACTIVE_IND) VALUES ('Adam.Etchison', 'password', 'Adam', 'Etchison', 5555555555, 'adam.etchison@daugherty.com', 1);

INSERT INTO ROLE (ROLE_CD, ROLE_NM) VALUES ('ROLE_ADMIN', 'Administrator');
INSERT INTO ROLE (ROLE_CD, ROLE_NM) VALUES ('ROLE_STUDENT', 'Student');
INSERT INTO ROLE (ROLE_CD, ROLE_NM) VALUES ('ROLE_INSTRUCTOR', 'Instructor');

INSERT INTO PERSONROLE (PERSON_ID, ROLE_ID) VALUES (3, 1); -- admin
INSERT INTO PERSONROLE (PERSON_ID, ROLE_ID) VALUES (1, 2);
INSERT INTO PERSONROLE (PERSON_ID, ROLE_ID) VALUES (1, 3);
INSERT INTO PERSONROLE (PERSON_ID, ROLE_ID) VALUES (2, 2);
INSERT INTO PERSONROLE (PERSON_ID, ROLE_ID) VALUES (2, 3);

INSERT INTO CLASSINSTANCE (CLASS_ID, CLASSINSTANCE_DT, CLASSINSTANCE_MINS, ROOM_ID, INSTRUCTOR_ID, CLASSINSTANCE_NOTE) VALUES (1, '2011-09-17 17:00:00', 90, 1, 1, 'Need to check on attendance.');

INSERT INTO ROSTER (CLASSINSTANCE_ID, PERSON_ID, ATTEND_IND) VALUES (1, 2, 1); -- John.Day attended above CLASSINSTANCE

INSERT INTO CLASSCOMMENT (ROSTER_ID, CLASSCOMMENT_TX, SCORE_INT) VALUES (1, 'I enjoyed the class.', 9);